--SQLite脚本 a.sql
 
--创建 PERSONS 类
CREATE TABLE PERSONS(
    ID INTEGER PRIMARY KEY,
    NAME TEXT NOT NULL COLLATE NOCASE,
    SEX CHAR NOT NULL,
    AGE INTEGER,
    TEL TEXT);
    
INSERT INTO PERSONS (NAME, SEX, AGE, TEL) 
    VALUES ('TSYBIUS', 'M', 23, '12345678901');
INSERT INTO PERSONS (NAME, SEX, AGE, TEL) 
    VALUES ('GALATEA', 'F', 21, '98765432109');
    
.quit

